INSERT INTO DEVELOPMENT_CARD(name, description, points, picked) VALUES
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Cavaleiro', 'Carta do cavaleiro', 0, 0),
('Catedral', 'Carta de 1 ponto', 1, 0),
('Mercado', 'Carta de 1 ponto', 1, 0),
('Câmara', 'Carta de 1 ponto', 1, 0),
('Biblioteca', 'Carta de 1 ponto', 1, 0),
('Universidade', 'Carta de 1 ponto', 1, 0),
('Monopólio', 'Carta de progresso', 0, 0),
('Monopólio', 'Carta de progresso', 0, 0),
('Invenção', 'Carta de progresso', 0, 0),
('Invenção', 'Carta de progresso', 0, 0),
('Construção de estradas', 'Carta de progresso', 0, 0),
('Construção de estradas', 'Carta de progresso', 0, 0);